package gitops

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/karpenter-optimizer/internal/recommender"
	"gopkg.in/yaml.v3"
)

type GitOpsConfig struct {
	Enabled       bool   `json:"enabled"`
	RepoPath      string `json:"repoPath,omitempty"`
	RepoURL       string `json:"repoUrl,omitempty"`
	Branch        string `json:"branch"`
	CommitMessage string `json:"commitMessage"`
	AutoPush      bool   `json:"autoPush"`
}

type ManifestGenerator struct {
	config *GitOpsConfig
}

func NewManifestGenerator(config *GitOpsConfig) *ManifestGenerator {
	if config.Branch == "" {
		config.Branch = "main"
	}
	if config.CommitMessage == "" {
		config.CommitMessage = "Update Karpenter NodePool recommendations"
	}

	return &ManifestGenerator{config: config}
}

func (g *ManifestGenerator) GenerateNodePoolManifests(recommendations []recommender.NodePoolRecommendation) ([]byte, error) {
	var manifests []map[string]interface{}

	for _, rec := range recommendations {
		manifest := g.createManifest(rec)
		manifests = append(manifests, manifest)
	}

	// Add comments/description as YAML document start
	var buf bytes.Buffer
	buf.WriteString("# Karpenter NodePool Recommendations\n")
	buf.WriteString("# Generated by Karpenter Optimizer\n")
	buf.WriteString(fmt.Sprintf("# Date: %s\n\n", time.Now().Format(time.RFC3339)))

	for _, manifest := range manifests {
		data, err := yaml.Marshal(manifest)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal manifest: %w", err)
		}
		buf.Write(data)
		buf.WriteString("---\n")
	}

	return buf.Bytes(), nil
}

func (g *ManifestGenerator) createManifest(rec recommender.NodePoolRecommendation) map[string]interface{} {
	manifest := map[string]interface{}{
		"apiVersion": "karpenter.sh/v1",
		"kind":       "NodePool",
		"metadata": map[string]interface{}{
			"name":        rec.Name,
			"annotations": map[string]string{},
		},
		"spec": map[string]interface{}{
			"template": map[string]interface{}{
				"spec": map[string]interface{}{
					"nodeClassRef": map[string]string{
						"name": "default",
					},
					"requirements": []map[string]interface{}{
						{
							"key":      "kubernetes.io/arch",
							"operator": "In",
							"values":   []string{rec.Architecture},
						},
						{
							"key":      "karpenter.sh/capacity-type",
							"operator": "In",
							"values":   []string{rec.CapacityType},
						},
					},
				},
			},
		},
	}

	// Add limits if specified
	if rec.Requirements.CPU.Max != "" || rec.Requirements.Memory.Max != "" {
		limits := make(map[string]string)
		if rec.Requirements.CPU.Max != "" {
			limits[rec.Requirements.CPU.Max] = ""
		}
		if rec.Requirements.Memory.Max != "" {
			limits[rec.Requirements.Memory.Max] = ""
		}
		manifest["spec"].(map[string]interface{})["limits"] = limits
	}

	// Add instance type requirements if specified
	if len(rec.InstanceTypes) > 0 {
		instanceTypes := make([]string, len(rec.InstanceTypes))
		for i, it := range rec.InstanceTypes {
			instanceTypes[i] = strings.Split(it, " ")[0]
		}

		requirements := manifest["spec"].(map[string]interface{})["template"].(map[string]interface{})["spec"].(map[string]interface{})["requirements"].([]map[string]interface{})
		requirements = append(requirements, map[string]interface{}{
			"key":      "node.kubernetes.io/instance-type",
			"operator": "In",
			"values":   instanceTypes,
		})
		manifest["spec"].(map[string]interface{})["template"].(map[string]interface{})["spec"].(map[string]interface{})["requirements"] = requirements
	}

	// Add description annotation
	reasoning := rec.Reasoning
	if len(reasoning) > 200 {
		reasoning = reasoning[:200] + "..."
	}
	manifest["metadata"].(map[string]interface{})["annotations"].(map[string]string)["karpenter.sh/description"] = reasoning

	return manifest
}

func (g *ManifestGenerator) WriteToFile(manifests []byte, filename string) error {
	if g.config.RepoPath == "" {
		return fmt.Errorf("repo path not configured")
	}

	dir := filepath.Join(g.config.RepoPath, "karpenter-nodepools")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory: %w", err)
	}

	path := filepath.Join(dir, filename)
	if err := os.WriteFile(path, manifests, 0644); err != nil {
		return fmt.Errorf("failed to write file: %w", err)
	}

	return nil
}

func (g *ManifestGenerator) CommitAndPush() error {
	if g.config.RepoPath == "" || !g.config.AutoPush {
		return nil
	}

	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	// Git add
	cmd := exec.CommandContext(ctx, "git", "-C", g.config.RepoPath, "add", ".")
	if output, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("git add failed: %w, output: %s", err, string(output))
	}

	// Git commit
	cmd = exec.CommandContext(ctx, "git", "-C", g.config.RepoPath, "commit", "-m", g.config.CommitMessage)
	if output, err := cmd.CombinedOutput(); err != nil {
		// Check if there's anything to commit
		if strings.Contains(string(output), "nothing to commit") {
			return nil
		}
		return fmt.Errorf("git commit failed: %w, output: %s", err, string(output))
	}

	// Git push
	if g.config.RepoURL != "" {
		cmd = exec.CommandContext(ctx, "git", "-C", g.config.RepoPath, "push", "origin", g.config.Branch)
		if output, err := cmd.CombinedOutput(); err != nil {
			return fmt.Errorf("git push failed: %w, output: %s", err, string(output))
		}
	}

	return nil
}

type PRCreator struct {
	githubToken string
	owner       string
	repo        string
}

func NewPRCreator(githubToken, owner, repo string) *PRCreator {
	return &PRCreator{
		githubToken: githubToken,
		owner:       owner,
		repo:        repo,
	}
}

func (p *PRCreator) CreatePullRequest(title, body, head, base string) (string, error) {
	if p.githubToken == "" {
		return "", fmt.Errorf("GitHub token not configured")
	}

	url := fmt.Sprintf("https://api.github.com/repos/%s/%s/pulls", p.owner, p.repo)

	payload := map[string]interface{}{
		"title": title,
		"body":  body,
		"head":  head,
		"base":  base,
	}

	jsonPayload, _ := json.Marshal(payload)
	req, _ := http.NewRequest("POST", url, bytes.NewBuffer(jsonPayload))
	req.Header.Set("Authorization", "token "+p.githubToken)
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	if resp.StatusCode != 201 {
		return "", fmt.Errorf("failed to create PR, status: %d", resp.StatusCode)
	}

	var result map[string]interface{}
	json.NewDecoder(resp.Body).Decode(&result)

	prURL, ok := result["html_url"].(string)
	if !ok {
		return "", fmt.Errorf("PR URL not found in response")
	}

	return prURL, nil
}

func LoadGitOpsConfigFromEnv() *GitOpsConfig {
	return &GitOpsConfig{
		Enabled:       getEnvBool("GITOPS_ENABLED", false),
		RepoPath:      getEnv("GITOPS_REPO_PATH", ""),
		RepoURL:       getEnv("GITOPS_REPO_URL", ""),
		Branch:        getEnv("GITOPS_BRANCH", "main"),
		CommitMessage: getEnv("GITOPS_COMMIT_MESSAGE", "Update Karpenter NodePool recommendations"),
		AutoPush:      getEnvBool("GITOPS_AUTO_PUSH", false),
	}
}

func getEnv(key, defaultValue string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return defaultValue
}

func getEnvBool(key string, defaultValue bool) bool {
	if value := os.Getenv(key); value != "" {
		return value == "true" || value == "1"
	}
	return defaultValue
}
