import yaml from 'js-yaml';

export const exportToJSON = (recommendations, filename = 'recommendations.json') => {
  const dataStr = JSON.stringify(recommendations, null, 2);
  downloadFile(dataStr, filename, 'application/json');
};

export const exportToYAML = (recommendations, filename = 'recommendations.yaml') => {
  const recommendationsForYaml = recommendations.map((rec) => ({
    apiVersion: 'karpenter.sh/v1',
    kind: 'NodePool',
    metadata: {
      name: rec.nodePoolName || rec.name,
    },
    spec: {
      template: {
        spec: {
          nodeClassRef: {
            name: 'default',
          },
          requirements: [
            { key: 'kubernetes.io/arch', operator: 'In', values: [rec.architecture || 'amd64'] },
            {
              key: 'karpenter.sh/capacity-type',
              operator: 'In',
              values: [rec.capacityType || 'spot'],
            },
            {
              key: 'karpenter.sh/nodepool',
              operator: 'In',
              values: [rec.nodePoolName || rec.name],
            },
          ],
        },
      },
      limits: {
        cpu: rec.recommendedTotalCPU ? `${Math.ceil(rec.recommendedTotalCPU)}` : undefined,
        memory: rec.recommendedTotalMemory
          ? `${Math.ceil(rec.recommendedTotalMemory)}Gi`
          : undefined,
        nodes: rec.recommendedNodes || 10,
      },
    },
  }));

  const yamlStr = yaml.dump(recommendationsForYaml, {
    indent: 2,
    lineWidth: 120,
    noRefs: true,
  });
  downloadFile(yamlStr, filename, 'text/yaml');
};

export const exportToKarpenterManifest = (
  recommendations,
  filename = 'karpenter-nodepools.yaml'
) => {
  const manifests = recommendations
    .map((rec) => {
      const manifest = {
        apiVersion: 'karpenter.sh/v1',
        kind: 'NodePool',
        metadata: {
          name: rec.nodePoolName || rec.name,
          annotations: {
            'karpenter.sh/description': rec.reasoning
              ? rec.reasoning.substring(0, 200)
              : 'Generated by Karpenter Optimizer',
          },
        },
        spec: {
          template: {
            spec: {
              nodeClassRef: {
                name: 'default',
              },
              requirements: [
                {
                  key: 'kubernetes.io/arch',
                  operator: 'In',
                  values: [rec.architecture || 'amd64'],
                },
                {
                  key: 'karpenter.sh/capacity-type',
                  operator: 'In',
                  values: [rec.capacityType || 'spot'],
                },
              ],
            },
          },
        },
      };

      if (rec.recommendedNodes > 0) {
        manifest.spec.limits = {
          nodes: rec.recommendedNodes,
        };
      }

      if (rec.recommendedInstanceTypes && rec.recommendedInstanceTypes.length > 0) {
        manifest.spec.template.spec.requirements.push({
          key: 'node.kubernetes.io/instance-type',
          operator: 'In',
          values: rec.recommendedInstanceTypes.map((it) => it.split(' ')[0]),
        });
      }

      return manifest;
    })
    .filter(Boolean);

  const yamlStr = yaml.dump(manifests, {
    indent: 2,
    lineWidth: 120,
    noRefs: true,
    sortKeys: false,
  });

  const header = `# Karpenter NodePools Generated by Karpenter Optimizer
# Date: ${new Date().toISOString()}
# Total NodePools: ${manifests.length}

`;
  downloadFile(header + yamlStr, filename, 'text/yaml');
};

const downloadFile = (content, filename, contentType) => {
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const generateSummary = (recommendations) => {
  const totalSavings = recommendations.reduce((sum, rec) => sum + (rec.costSavings || 0), 0);
  const totalCurrentCost = recommendations.reduce((sum, rec) => sum + (rec.currentCost || 0), 0);
  const totalRecommendedCost = recommendations.reduce(
    (sum, rec) => sum + (rec.recommendedCost || 0),
    0
  );

  return {
    totalRecommendations: recommendations.length,
    totalCurrentCost,
    totalRecommendedCost,
    totalSavings,
    savingsPercent: totalCurrentCost > 0 ? ((totalSavings / totalCurrentCost) * 100).toFixed(1) : 0,
  };
};
